name: Deploy SolidaryTech

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to apply Terraform"
        required: true
        type: choice
        options:
          - development
          - staging
          - production
          - disaster_recovery
      confirm:
        description: "Type the environment name to confirm"
        required: true

jobs:

  #Validação para evitar deploy acidental
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "${{ github.event.inputs.environment }}" ]; then
            echo "Confirmation '${{ github.event.inputs.confirm }}' does not match environment '${{ github.event.inputs.environment }}'."
            exit 1
          fi

  # 0. Bootstrap Terraform
  Bootstrap_Terraform:
    needs: validate
    uses: SolidaryTech-Project/Infrastructure/.github/workflows/terraform_bootstrap.yaml@main
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      aws-region: ${{ github.event.inputs.environment == 'disaster_recovery' && vars.AWS_REGION_DR || vars.AWS_REGION }}
      terraform_version: ${{ vars.TF_VERSION }}

  # 1. Aplicar Infra
  Terraform:
    needs: Bootstrap_Terraform
    uses: SolidaryTech-Project/Infrastructure/.github/workflows/terraform_apply.yaml@main
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      aws-region: ${{ github.event.inputs.environment == 'disaster_recovery' && vars.AWS_REGION_DR || vars.AWS_REGION }}
      terraform_version: ${{ vars.TF_VERSION }}

  # 3. Deploy Observability (Datadog)
  Observability:
    needs: Terraform
    uses: SolidaryTech-Project/Observability/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}

  # 4. CI dos Microserviços (Rodam em paralelo)
  CI_NGO:
    #needs: Observability
    needs: Observability
    uses: SolidaryTech-Project/NGO-Service/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      aws-region: ${{ github.event.inputs.environment == 'disaster_recovery' && vars.AWS_REGION_DR || vars.AWS_REGION }}
      python-version: ${{ vars.PYTHON_VERSION }}

  CI_Donation:
    #needs: Observability
    needs: Observability
    uses: SolidaryTech-Project/Donation-Service/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      aws-region: ${{ github.event.inputs.environment == 'disaster_recovery' && vars.AWS_REGION_DR || vars.AWS_REGION }}

  CI_Volunteer:
    #needs: Observability
    needs: Observability
    uses: SolidaryTech-Project/Volunteer-Service/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      aws-region: ${{ github.event.inputs.environment == 'disaster_recovery' && vars.AWS_REGION_DR || vars.AWS_REGION }}
      python-version: ${{ vars.PYTHON_VERSION }}

  # 5. Deploy Final com ArgoCD e Helm
  Deploy_Helm:
    needs: [CI_NGO, CI_Donation, CI_Volunteer] # Espera os CIs terminarem
    uses: SolidaryTech-Project/SolidaryTech/.github/workflows/cd.yaml@main
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      aws-region: ${{ github.event.inputs.environment == 'disaster_recovery' && vars.AWS_REGION_DR || vars.AWS_REGION }}